version: "2"
volumes:
  config:
  venv:
services:
  octoprint:
    build: .
    # image: kumekay/octoprint
    container_name: octoprint
    ports:
      - 80:5000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - config:/home/octoprint/.octoprint
      - venv:/opt/octoprint/venv
